# Generated by Django 5.1.2 on 2024-10-14 08:27

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bankaccounttype_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='interest_start_date',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='bank_name',
            field=models.CharField(default='20241014082712', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
