# Generated by Django 5.1.2 on 2024-10-14 08:37

import accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_type',
            field=models.ForeignKey(default='20241014083715', on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_accounts', to='accounts.bankaccounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='interest_start_date',
            field=models.DateField(blank=True, help_text='The month number that interest calculation will start from', null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
