# Generated by Django 5.1.2 on 2024-10-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_type',
        ),
        migrations.DeleteModel(
            name='BankAccountType',
        ),
    ]
