# Generated by Django 5.1.2 on 2024-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_supportticket_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='solution',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
