# Generated by Django 5.1.2 on 2024-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportticket_solution_alter_supportticket_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='solution',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
