# Generated by Django 5.1.2 on 2024-10-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_flagged_transaction_reverted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
