# Generated by Django 5.1.2 on 2024-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
