# Generated by Django 5.1.2 on 2024-10-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
