# Generated by Django 5.1.2 on 2024-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_fraudreport_fraudreportaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudreportaction',
            name='fraud_report',
        ),
        migrations.RemoveField(
            model_name='fraudreportaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='FraudReport',
        ),
        migrations.DeleteModel(
            name='FraudReportAction',
        ),
    ]
