# Generated by Django 5.1.2 on 2024-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loancategory_loan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default=1111111111, editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
