# Generated by Django 5.1.2 on 2024-11-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
